DROP SCHEMA IF EXISTS poetica_sonora CASCADE;

DROP SCHEMA IF EXISTS audit CASCADE;

CREATE SCHEMA poetica_sonora AUTHORIZATION davidlum;

--CREATE USER aurelio WITH NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN;

