INSERT INTO institucion (institucion_nom, lugar_id, tipo_inst) VALUES
('Radio Educación', 58, 1),
('Universidad Nacional Autónoma de México', 58, 2),
('Fonoteca Nacional', 58, 3),
('Soundcloud', 115, 4),
('Bandcamp', 116, 4),
('YouTube', 117, 4),
('Ex-Teresa Arte Actual', 58, 5),
('Laboratorio de Arte Alameda', 58, 5),
('Concordia University', 123, 2),
('Colegio de la Frontera Norte', 69, 2),
('Colegio de México', 58, 2),
('Colegio Nacional', 58, 2),
('Fondo de Cultura Económica', 58, 6),
('Pentagrama', 58, 7),
('Festival Verbo', 58, 8),
('Pluralia', 58, 6),
('Centro de Cultura Digital', 58, 9);