INSERT INTO instrumento (nom_inst, familia_instr_id, electronico, instrumento_comentario) VALUES
('Ninguno', 1, 'f', 'No se identificaron instrumentos'),
('Sintetizador digital', 12, 't', 'Genera señales eléctricas que a su vez son convertidas a sonidos a través de bocinas o audífonos'),
('Programa de computadora', 14, 't', 'Programa de computadora no identificado'),
('Radio', 13, 'f', 'Uso de tecnologías radiofónicas con fines creativos'),
('Cazuela', 9, 'f', 'Cazuela utilizada con fines creativos'),
('Instrumento de cuerdas', 7, 'f', 'Instrumento de cuerdas no identificado'),
('Modulador de voz', 15, 't', 'Marca y modelo no identificados'),
('Sintetizador analógico', 13, 'f', 'Sintetizador que utiliza circuitos y señales analógicas para generar sonidos electrónicamente'),
('FL Studio', 14, 't', 'Antes llamado Fruity Loops; estación de trabajo de audio digital de Image-line Software con las características de editor de audio, secuenciador con soporte multipista y MIDI utilizado para la producción musical'),
('Adobe Audition', 14, 't', 'Antes llamado Cool Edit Pro; estación de trabajo de audio digital de Adobe dedicada a la edición de audio digital que permite entornos de edición y mezcla de ondas multipista tanto destructivos como no destructivos'),
('Line6 DL4', 15, 't', 'Pedal de efectos digital que emula los modelos de sinidos de unidades previas, como Maestro EP-1 Echoplex o el Roland RE-101, y que se ha vuelto un clásico por derecho propio'),
('Guitarra acústica', 7, 'f', 'Instrumento musical armónico de cuerda bien templada que cuenta con caja de resonancia para la amplificación del sonido producido por la vibración de las cuerdas, mástil, diapasón o trastero, clavijero y el puente donde se colocan las cuerdas'),
('Guitarra eléctrica', 7, 'f', 'Instrumento musical armónico y melódico de seis cuerdas que utiliza el principio de inducción electromagnética para convertir las vibraciones de sus cuerdas de metal en señales eléctricas'),
('Guitarra electro-acústica', 1, 'f', 'Instrumento musical armónico equipado con pastillas, un micrófono o transductores'),
('Guitarra de juguete', 7, 'f', 'Juguete con forma de guitarra acústica utilizado con fines creativos'),
('Guitarra', 1, 'f', 'Tipo de guitarra no identificado'),
('Piano', 12, 'f', 'Instrumento musical acústico de cuerdas que son golpeadas por martillos a través de un teclado operado con los dedos de las manos'),
('Palmas', 10, 'f', 'Uso de las manos para generar diversos sonidos percusivos, como aplausos o chasquidos'),
('Xilófono', 9, 'f', 'Consiste de barras de madera con diversas tesituras, golpeadas con martillos que son operados manualmente'),
('Grabadora', 3, 'f', 'Uso de una grabadora de audio, así como de los sonidos generados por ella, con fines creativos'),
('Micrófono', 3, 'f', 'Uso de un micrófono para modificar o alterar diversos elementos sonoros, como el timbre y la tesitura, con fines creativos o estéticos'),
('Bajo eléctrico', 7, 'f', 'Instrumento musical melódico de la familia de los cordófonos, similar en apariencia y construcción a la guitarra eléctrica, pero con un mástil de mayor longitud y escala y (normalmente) cuatro cuerdas que siguen la afinación estándar del contrabajo, su antecesor'),
('Tambor', 8, 'f', 'Tipo de tambor no identificado'),
('Batería', 11, 'f', 'Conjunto de instrumentos musicales de percusión que por lo general consistente de diversos platillos, toms, bombos y tarolas'),
('Piernas', 10, 'f', 'Uso de las piernas y sus vestimentas para generar diversos sonidos percusivos, como pisadas, taconeos, zapateos, entre otros'),
('Percusiones', 11, 'f', 'Instrumento de percusión no identificado'),
('Sonaja', 9, 'f', 'Agrupaciones de chapas de metal atravesadas por uno o más alambres sujetos a un aro en forma de círculo o semicírculo, o bien otro tipo de bases, como rectángulos de madera o plástico, con manija o sin ella, etc. La emisión sonora se consigue mediante agitamiento o golpeo'),
('Caja de ritmos', 15, 'f', 'Marca y modelo no identificados');
