INSERT INTO genero_artista (genero_nom) VALUES
  ('Sin género'),
  ('Andrógino'),
  ('Andrógina'),
  ('Andróginx'),
  ('Bigénero'),
  ('Cis'),
  ('Cis femenina'),
  ('Cis masculino'),
  ('Cis hombre'),
  ('Cis mujer'),
  ('Cisgénero'),
  ('Cisgénero femenina'),
  ('Cisgénero masculino'),
  ('Cisgénero hombre'),
  ('Cisgénero mujer'),
  ('Mujer a hombre'),
  ('FTM'),
  ('Género fluido'),
  ('Inconforme con el género'),
  ('Cuestionando al género'),
  ('Variante de género'),
  ('Genderqueer'),
  ('Intersexo'),
  ('Hombre a mujer'),
  ('MTF'),
  ('Ninguno'),
  ('Neutro'),
  ('No binario'),
  ('Otro'),
  ('Pangénero'),
  ('Trans'),
  ('Trans femenina'),
  ('Trans masculino'),
  ('Hombre trans'),
  ('Persona trans'),
  ('Trans*femenina'),
  ('Trans*masculino'),
  ('Trans*hombre'),
  ('Trans*persona'),
  ('Trans*mujer'),
  ('Transexual'),
  ('Transexual femenina'),
  ('Transexual masculino'),
  ('Hombre transexual'),
  ('Persona transexual'),
  ('Mujer transexual'),
  ('Transgénero femenina'),
  ('Persona Transgénero'),
  ('Transmasculino'),
  ('Dos espíritus'),
  ('Asexual'),
  ('Hombre trans mujer a hombre'),
  ('Hombre transgénero mujer a hombre'),
  ('Hombre transexual mujer a hombre'),
  ('F2M'),
  ('Neutral con el género'),
  ('Hermafrodita'),
  ('Hombre intersexo'),
  ('Persona intersexo'),
  ('Mujer intersexo'),
  ('Mujer trans hombre a mujer'),
  ('Mujer transgénero hombre a mujer'),
  ('Mujer transexual hombre a mujer'),
  ('Hombre'),
  ('M2F'),
  ('Poligénero'),
  ('Hombre T*'),
  ('Mujer T*'),
  ('Persona dos*'),
  ('Persona de dos espíritus'),
  ('Mujer');