INSERT INTO artista (nom_primero, nom_segundo, paterno_nom, materno_nom, seudonimo, fecha_nac, lugar_nac, fecha_muer, lugar_muer, genero_id) VALUES
('Manuel', NULL, 'Maples', 'Arce', NULL, '1898-05-01', 137, '1981-06-16', 58, 64),
('Diego', NULL, 'Rivera', NULL, NULL, '1886-12-08', 61, '1957-11-24', 58, 64),
('Luis', NULL, 'Quintanilla', NULL, 'Kin Taniya', '1900-11-22', 62, '1980-03-16', 1, 64),
('Jorge', NULL, 'Reyes', NULL, NULL, '1952-01-01', 63, '2009-01-01', 1, 64),
('Jaime', NULL, 'Torres', 'Bodet', NULL, '1902-04-17', 58, '1974-05-13', 58, 64),
('Xavier', NULL, 'Villaurrutia', NULL, NULL, '1903-03-27', 58, '1950-12-25', 58, 64),
('Juan', 'Nepomuceno', 'Pérez', 'Rulfo', 'Juan Rulfo', '1917-05-16', 130, '1986-01-07', 58, 64),
('Leonard', NULL, 'Bernstein', NULL, NULL, '1918-08-25', 131, '1990-10-14', 132, 64),
('Francisco', NULL, 'Gabilondo', 'Soler', 'Cri-Cri', '1907-10-06', 133, '1990-12-14', 134, 64),
('Salvador', NULL, 'Díaz', 'Mirón', NULL, '1853-12-14', 64, '1928-06-12', 64, 64);

INSERT INTO artista (nom_primero, nom_segundo, paterno_nom, materno_nom, seudonimo, lugar_nac, genero_id, coment_autor) VALUES
('Desconocido', NULL, NULL, NULL, NULL, 1, 29, 'Nombre, género y origen desconocidos'), 
('Desconocido', NULL, NULL, NULL, NULL, 2, 71, 'Mujer mexicana, nombre desconocido'),
('Desconocido', NULL, NULL, NULL, NULL, 2, 64, 'Hombre mexicano, nombre desconocido'),
('Desconocido', NULL, NULL, NULL, NULL, 5, 71, 'Mujer chilena, nombre desconocido');

INSERT INTO artista (nom_primero, nom_segundo, paterno_nom, materno_nom, seudonimo, fecha_nac, lugar_nac, genero_id) VALUES
('Mario', NULL, 'Mota', 'Martínez', NULL, 'desconocido', 58, 64),
('Víctor', 'Manuel', 'Rivas', 'Dávalos', NULL, '1970-00-00', 59, 64),
('Anabella', NULL, 'Solano', NULL, NULL, 'desconocido', 58, 71),
('Gildardo', NULL, 'Cruz', 'Rojas', NULL, 'desconocido', 2, 64),
('César', NULL, 'Cortés', 'Vega', NULL, 'desconocido', 58, 64),
('Edmeé', NULL, 'García', NULL, 'Diosa Loca', '1984-00-00', 58, 71),
('Leika', NULL, 'Mochán', NULL, NULL, 'desconocido', 2, 71),
('Iraida', NULL, 'Noriega', NULL, NULL, '1971-00-00', 58, 71),
('Juan', 'Manuel', 'Torreblanca', NULL, NULL, '1981-00-00', 58, 64),
('Desconocido', NULL, NULL, NULL, 'Homodon', '1985-00-00', 58, 64),
('Mario', NULL, 'Dux', 'Castel', NULL, '1971-00-00', 58, 64),
('Édgar', NULL, 'Torres', NULL, NULL, 'desconocido', 2, 64),
('Juan', 'Joaquín', 'Pérez', 'Tejeda', NULL, '1962-00-00', 55, 64),
('Iván', NULL, 'Torres', 'Salguero', 'Van-T', '1976-00-00', 58, 64),
('Adolfo', NULL, 'Guzmán', 'López', NULL, '1969-00-00', 58, 64),
('Ulises', NULL, 'López', NULL, 'Sad C', '1984-00-00', 58, 64),
('Logan', NULL, 'Phillips', NULL, NULL, '1983-00-00', 65, 64),
('Mónica', NULL, 'González', NULL, NULL, '1973-00-00', 58, 71),
('Yaxkin', NULL, 'Melchy', 'Ramos', NULL, '1985-00-00', 58, 64),
('Desconocido', NULL, NULL, NULL, 'MC Ewor', '1989-00-00', 58, 64),
('Guillermo', NULL, 'Henry', NULL, NULL, '1954-00-00', 58, 64),
('Eduardo', NULL, 'Ribé', NULL, NULL, '1984-00-00', 66, 64),
('Rojo', NULL, 'Córdova', NULL, NULL, '1986-00-00', 58, 64),
('Javier', NULL, 'Raya', NULL, NULL, '1985-00-00', 58, 64),
('Edgar', NULL, 'Conde', NULL, 'Edgar Khonde', '1979-00-00', 58, 64),
('Desconocido', NULL, NULL, NULL, 'MC L-On', '1983-00-00', 58, 64),
('Mauricio', NULL, 'Jiménez', NULL, 'Miauricio Jiménez Morocco', '1979-00-00', 58, 64),
('Carlos', 'Ascención', 'Ramírez', 'Méndez', 'Karloz Atl', '1988-00-00', 58, 64),
('Sara', NULL, 'Ra', 'Ca', 'Sara Raca', '1981-00-00', 67, 71),
('Javier', NULL, 'Moro', NULL, NULL, '1976-00-00', 58, 64),
('Carlos', NULL, 'Ramírez', NULL, 'Kobra', '1984-00-00', 68, 64),
('Adrián', NULL, 'Sánchez', 'Ramírez', 'Tenocht40', 'desconocido', 58, 64);

INSERT INTO artista (nom_primero, nom_segundo, paterno_nom, materno_nom, seudonimo, fecha_nac, lugar_nac, genero_id) VALUES
('Desconocido', NULL, NULL, NULL, 'Rashid', 'desconocido', 2, 64),
('Desconocido', NULL, NULL, NULL, 'Besty Numen', 'desconocido', 2, 71),
('Desconocido', NULL, NULL, NULL, 'Ahuizotl', 'desconocido', 2, 64),
('Desconocido', NULL, NULL, NULL, 'Basher', 'desconocido', 2, 64),
('Desconocido', NULL, NULL, NULL, 'Bronte', 'desconocido', 2, 64),
('Desconocido', NULL, NULL, NULL, 'DonNet', 'desconocido', 2, 64),
('Desconocido', NULL, NULL, NULL, 'El Violín', 'desconocido', 2, 64),
('Desconocido', NULL, NULL, NULL, 'El Ave Gris', 'desconocido', 2, 71),
('Desconocido', NULL, NULL, NULL, 'Susanita', 'desconocido', 2, 64),
('Desconocido', NULL, NULL, NULL, 'Filosoflow', 'desconocido', 2, 64),
('Desconocido', NULL, NULL, NULL, 'Furor Sanandi', 'desconocido', 2, 64),
('Abelardo', NULL, NULL, NULL, 'Tribilín', 'desconocido', 2, 64),
('Daniel', NULL, NULL, NULL, NULL, 'desconocido', 2, 64),
('Desconocido', NULL, NULL, NULL, 'Mondragón', 'desconocido', 2, 64),
('Hugo', NULL, NULL, NULL, 'Cóatl', 'desconocido', 2, 64),
('Victoria', NULL, 'Tyler', NULL, NULL, 'desconocido', 2, 71),
('Nuber', NULL, 'Limón', NULL, NULL, 'desconocido', 2, 71),
('Javier', NULL, 'Jiménez', NULL, NULL, 'desconocido', 2, 64),
('Jesús', NULL, 'Bravo', NULL, NULL, 'desconocido', 2, 64),
('Jahir', NULL, NULL, NULL, NULL, 'desconocido', 2, 64),
('Homero', NULL, NULL, NULL, NULL, 'desconocido', 2, 64),
('Renato', NULL, NULL, NULL, NULL, 'desconocido', 2, 64),
('Luis', NULL, NULL, NULL, 'Ro', 'desconocido', 2, 64),
('José', NULL, 'Gudma', NULL, NULL, 'desconocido', 2, 64),
('Jorge', NULL, NULL, NULL, 'Pos', 'desconocido', 2, 64),
('Juan', 'Pablo', NULL, NULL, NULL, 'desconocido', 2, 64),
('Carla', NULL, 'Páez', NULL, NULL, 'desconocido', 2, 71),
('Mayra', NULL, 'Cheta', NULL, NULL, 'desconocido', 2, 71),
('Jonatan', NULL, 'Hernández', 'Barreda', 'Huachimingo o Santi Balmes', 'desconocido', 2, 64),
('Lucía', NULL, NULL, NULL, NULL, 'desconocido', 4, 71),
('Alejandra', NULL, NULL, NULL, NULL, 'desconocido', 2, 71),
('Dan', NULL, NULL, NULL, NULL, 'desconocido', 2, 71),
('Carlos', NULL, 'Pineda', NULL, NULL, 'desconocido', 2, 64),
('Alan', NULL, NULL, NULL, NULL, 'desconocido', 2, 64),
('Alan', NULL, 'Casas', NULL, NULL, 'desconocido', 2, 64),
('Alberto', NULL, 'Martínez', NULL, NULL, 'desconocido', 2, 64),
('Alberto', NULL, 'Velázquez', NULL, NULL, 'desconocido', 2, 64),
('Alejandro', NULL, NULL, NULL, NULL, 'desconocido', 2, 64),
('Alfredo', NULL, 'Santiago', NULL, NULL, 'desconocido', 2, 64),
('América', NULL, NULL, NULL, NULL, 'desconocido', 2, 71),
('Ana', 'Paula', NULL, NULL, NULL, 'desconocido', 2, 71),
('Andrés', NULL, 'Galindo', NULL, 'Ixca Cienfuegos', 'desconocido', 2, 64),
('Ánuar', NULL, 'Zúñiga', 'Naime', NULL, 'desconocido', 2, 64),
('Arange', NULL, 'Verdí', NULL, NULL, 'desconocido', 6, 71),
('Caco', NULL, 'Pontes', NULL, NULL, 'desconocido', 10, 64),
('Paula', NULL, 'Klein', NULL, NULL, 'desconocido', 10, 71),
('Carlos', NULL, 'Barraza', NULL, 'Titos', 'desconocido', 58, 64),
('Christian', NULL, 'Partida', NULL, NULL, 'desconocido', 2, 64),
('Cinthia', NULL, NULL, NULL, 'Candelas', 'desconocido', 2, 71),
('Roberto', 'Iván', 'Mendoza', 'Gomez', 'Comikk MG', '1988-00-00', 58, 64),
('Coral', NULL, 'Bracho', NULL, NULL, '1951-05-22', 58, 71),
('Cristian', NULL, NULL, NULL, NULL, 'desconocido', 2, 64),
('Alfredo', NULL, 'Cruz', 'Del Rosal', NULL, 'desconocido', 2, 64),
('Daniel', NULL, 'Goli', NULL, NULL, 'desconocido', 2, 64),
('David', NULL, NULL, NULL, NULL, 'desconocido', 2, 64),
('David', NULL, NULL, NULL, 'C', 'desconocido', 2, 64),
('Diego', NULL, 'Medina', NULL, 'Diego Pingüino', 'desconocido', 2, 64),
('Edwing', NULL, 'Roldán', 'Ortíz', 'Canuto', '1988-05-17', 58, 64),
('Elsa', NULL, 'Cross', NULL, NULL, '1946-03-06', 58, 71),
('Emiliano', NULL, 'Mora', NULL, NULL, 'desconocido', 2, 64),
('Emiliano', NULL, 'Reyes', NULL, NULL, 'desconocido', 2, 64),
('Ernesto', NULL, NULL, NULL, 'Salamandra', 'desconocido', 2, 64),
('Faro', NULL, NULL, NULL, 'Zak', 'desconocido', 2, 64),
('Fernando', NULL, NULL, NULL, NULL, 'desconocido', 2, 64),
('Frida', NULL, 'Trejo', NULL, NULL, 'desconocido', 2, 71),
('Francisco', NULL, 'Romero', NULL, NULL, 'desconocido', 2, 64),
('Jesús', 'Antonio', 'Rodríguez', NULL, 'Frino', '1977-00-00', 32, 64),
('Frisia', NULL, 'Guerrero', NULL, NULL, 'desconocido', 2, 71),
('Galinas', NULL, NULL, NULL, NULL, 'desconocido', 3, 71),
('Hebe', NULL, 'Rosell', NULL, NULL, 'desconocido', 4, 71),
('Héctor', NULL, 'Villareal', NULL, NULL, 'desconocido', 2, 64),
('Irma', NULL, 'Pineda', 'Santiago', NULL, '1974-00-00', 129, 71),
('Isabel', NULL, NULL, NULL, NULL, 'desconocido', 2, 71),
('Israel', NULL, NULL, NULL, NULL, 'desconocido', 2, 64),
('Jessica', NULL, 'Carrasco', NULL, NULL, 'desconocido', 2, 71),
('Johnny', NULL, NULL, NULL, NULL, 'desconocido', 2, 64),
('Julieta', NULL, NULL, NULL, NULL, 'desconocido', 2, 71),
('Karla', NULL, 'Páez', NULL, NULL, 'desconocido', 2, 71),
('Kashian', NULL, 'Sagredo', NULL, NULL, 'desconocido', 2, 71),
('Kevin', NULL, 'Mara', NULL, 'Kev Mara', 'desconocido', 2, 64),
('Desconocido', NULL, NULL, NULL, 'Kilamastra', 'desconocido', 2, 64),
('Desconocido', NULL, NULL, NULL, 'Josuelfo', 'desconocido', 2, 64),
('Jorge', NULL, 'Sosa', NULL, NULL, 'desconocido', 2, 64),
('Jorge', NULL, 'Posada', NULL, 'Costa sin mar', '1980-00-00', 58, 64),
('Andrei', NULL, 'Vásquez', NULL, NULL, 'desconocido', 2, 64),
('Rodrigo', NULL, 'Román', NULL, NULL, 'desconocido', 2, 64),
('Óliver', 'H', 'Incháustegui', NULL, NULL, 'desconocido', 2, 64),
('Gerardo', NULL, 'Ocejo', NULL, NULL, 'desconocido', 2, 64),
('Desconocido', NULL, NULL, NULL, 'Maiiky Trauma', 'desconocido', 2, 64),
('Desconocido', NULL, NULL, NULL, 'Majo', 'desconocido', 2, 71),
('Desconocido', NULL, NULL, NULL, 'Malayonki', 'desconocido', 2, 64),
('Desconocido', NULL, NULL, NULL, 'Manu Roten', 'desconocido', 2, 64),
('Mariana', NULL, 'Hera', NULL, NULL, 'desconocido', 2, 71),
('Mariel', NULL, 'Martínez', NULL, NULL, 'desconocido', 2, 71),
('Desconocido', NULL, NULL, NULL, 'Morris M', 'desconocido', 2, 64),
('Mónica', NULL, 'Gameros', NULL, NULL, '1971-00-00', 58, 71),
('Desconocido', NULL, NULL, NULL, 'Morton', 'desconocido', 2, 64),
('Desconocido', NULL, NULL, NULL, 'Nómada', 'desconocido', 2, 64),
('Desconocido', NULL, NULL, NULL, 'Pito Amor', 'desconocido', 2, 64),
('Desconocido', NULL, NULL, NULL, 'Rashid', 'desconocido', 2, 64),
('Patricio', NULL, 'Hernández', 'Lebeau', 'Pat Lebeau', 'desconocido', 2, 64),
('Raúl', NULL, 'Avilés', NULL, NULL, 'desconocido', 2, 64),
('María', 'Roselia', 'Jiménez', 'Pérez', NULL, '1959-00-00', 126, 71),
('Desconocido', NULL, NULL, NULL, 'Said', 'desconocido', 2, 64),
('Santiago', NULL, NULL, NULL, 'Dei', 'desconocido', 2, 64),
('Saúl', NULL, 'Fimbres', NULL, NULL, 'desconocido', 2, 64),
('Desconocido', NULL, NULL, NULL, 'Shah Mat', 'desconocido', 2, 64),
('Desconocido', NULL, NULL, NULL, 'Spring Ramírez', 'desconocido', 2, 64),
('Desconocido', NULL, NULL, NULL, 'Sra. Tormenta', 'desconocido', 2, 71),
('Desconocido', NULL, NULL, NULL, 'Vankai', 'desconocido', 2, 64),
('Xicoténcatl', NULL, NULL, NULL, NULL, 'desconocido', 2, 64),
('Desconocido', NULL, NULL, NULL, 'Yabs Garigoleo', 'desconocido', 2, 64),
('Desconocido', NULL, NULL, NULL, 'Yaushu', 'desconocido', 2, 71),
('Alexis', NULL, 'Díaz', 'Pimienta', NULL, '1966-00-00', 127, 64),
('Refugio', NULL, 'Solís', NULL, NULL, 'desconocido', 2, 71),
('Angie', NULL, 'Sandoval', NULL, NULL, 'desconocido', 2, 71),
('Hugo', NULL, 'Palacios', NULL, NULL, 'desconocido', 2, 64),
('Angélica', NULL, 'Cortés', NULL, NULL, 'desconocido', 2, 71),
('Guillermo', NULL, 'Lagarde', NULL, NULL, 'desconocido', 2, 64),
('Mario', NULL, 'Pulido', NULL, NULL, 'desconocido', 2, 64),
('Gabriela', NULL, 'Sosa', NULL, NULL, 'desconocido', 2, 71),
('Emilio', NULL, 'Eberjenyi', NULL, NULL, 'desconocido', 2, 64),
('Pepe', NULL, 'González', 'Márquez', NULL, 'desconocido', 2, 64),
('Hénri', NULL, 'Béhar', NULL, NULL, '1940-05-28', 62, 64),
('Michel', NULL, 'Carassou', NULL, NULL, 'desconocido', 128, 64),
('José', NULL, 'Martínez', 'Sotomayor', NULL, 'desconocido', 2, 64),
('Stephen', 'Joshua', 'Sondheim', NULL, NULL, '1930-03-22', 132, 64),
('Nico', NULL, NULL, NULL, NULL, 'desconocido', 2, 64),
('Paulina', NULL, 'Fuentes', NULL, NULL, 'desconocido', 2, 71),
('Gordon', 'Matthew', 'Thomas', 'Sumner', 'Sting', '1951-10-02', 135, 64);