INSERT INTO composicion (nom_tit) VALUES
('A propósito del poeta muerto'),
('Sinicuichi'),
('Iuiuiu'),
('Las madres de las muertas de Juárez'),
('Poema prisma'),
('Reflejos'),
('Dadá Cabaret Voltaire'),
('La rueca del aire'),
('Canto a la muerte'),
('Itinerario de la memoria'),
('La guerra es una locura extrema'),
('Té - Invitación'),
('Aclaración'),
('Ars poetica'),
('Risa'),
('Espejo'),
('Mae Yong'),
('Patria'),
('Señor del sueño'),
('Nada me saca de la cama'),
('Ajedrez'),
('La mosquita muerta'),
('Tibio'),
('Roto corazón'),
('Mi mamá está triste'),
('Lunática'),
('La muñeca fea'),
('Sigo intentando'),
('Frágil'),
('La chilanga'),
('Los sonidos que me guardé'),
('Aves de verano/Suite para peces'),
('"¿Cuál es la medida exacta del verso...?"'),
('"Aire enrarecido..."'),
('"Antes eran copias de Fermín..."'),
('"Cada noche siempre llego muy puntual..."'),
('"Ciudad donde me miras dormida..."'),
('"Con el tiempo..."'),
('"Cuando tú bailas el son..."'),
('Cumbia esta noche para toda la gente'),
('"Debajo de las nubes..."'),
('"Ellos, los que matas y encierran..."'),
('"En cierta forma..."'),
('"En primavera veo el sol salir..."'),
('"Escribo donde libros..."'),
('"Espero que tu alarma no suene..."'),
('Espero tu llegada...'),
('"Esta minificción..."'),
('"Estábamos en guerra..."'),
('"Esto es un micrófono humano de poesía..."'),
('"Estoy cansado..."'),
('"Hora 2:50..."'),
('"Hoy soñé que..."'),
('"Ibas a cambiar el mundo..."'),
('"La ciudad de tres pisos..."'),
('"Las neuronas se apagan..."'),
('"Limoncito levanta los estragos..."'),
('"Llévame a ahogar..."'),
('"Mira puedes ser..."'),
('"Murmuro todo en sacrificio de esa respuesta..."'),
('"No hay sentido que me haga despertar..."'),
('"No sé si me cosieron al mito..."'),
('"No te conozco..."'),
('"No votamos, no callamos..."'),
('"Nos volvimos a mirar..."'),
('"Nos volvimos a caer..."'),
('"Posterior al rostro..."'),
('"Puedo jugar con la muerte..."'),
('"Romperte en mil pedazos..."'),
('"Se trata de esa frecuencia absoluta..."'),
('"Señorita Laura..."'),
('"Si tuviera un peso..."'),
('"Soy árbol..."'),
('"Soy la aurora forjada en el uiverso..."'),
('"Te prometes a ti mismo..."'),
('"Todavía hay habitantes en la luz..."'),
('"Tu habilidad para pescar fue un buen pretexto..."'),
('"Uno: Sombras..."'),
('"Vi la lluvia caer..."'),
('"Vienes de nuevo..."'),
('"Y la rima empieza aquí adentro..."'),
('"Y otra vez la misma melodía..."'),
('"Ya llegó su pachucote..."'),
('"Ya me dijeron, ya me contaron..."'),
('"Yo de niño era una persona extraña..."'),
('"Yo tengo que invocar al agua..."'),
('"Yo zapateo con destreza..."'),
('¿De cuántos puentes en el mundo podré decir que alguno es mío?'),
('¿Qué historia?'),
('¿Qué transita por las venas?'),
('01011001'),
('A B'),
('A la mierda'),
('Acto de contrición'),
('Acuarela'),
('Ahora el dólar alza el vuelo'),
('Algo más allá del amor'),
('Alguien se equivocó al ponerme aquí'),
('Amor mío'),
('Analogías'),
('Antimaterno'),
('Aqua'),
('Árbol sin ataduras'),
('Atole'),
('Autonmincor'),
('Azules'),
('Balabras'),
('Banner'),
('Buenas muertes'),
('Camarones'),
('Camino'),
('Caretera'),
('Carver'),
('Ciudadana Kane'),
('Clavadista'),
('Colibrí'),
('Comentario a un poema que habla sobre perros'),
('Con el fuego dentro'),
('Congestión'),
('Construye un templo imaginario'),
('Coracao'),
('"Corto la máscara..."'),
('D.F.'),
('De "Abrazo de árbol"'),
('De dos'),
('Después de todo'),
('Dialéctica'),
('Dulce muerte querida'),
('Él'),
('El clavadista'),
('El dolor'),
('El duende'),
('El mar'),
('El misterio de tus pinches ojos'),
('El poeta se expande'),
('El sentido de un latido no es un ruido'),
('El Sun Tzu de la supermanzana'),
('Ellos no tienen voces'),
('En este mundo'),
('Enciende el televisor'),
('Es un hecho'),
('Escape'),
('Etnalera'),
('Fantasma'),
('Felipe Granados'),
('Fiesta de disfraces'),
('Fui la noite'),
('Gerusalem'),
('Hay días grises de repente'),
('Hip Hop'),
('Iluminaciones que hace la cuenta'),
('Increíbles sensaciones de una experiencia erótica'),
('Inefable'),
('Intro'),
('Ir al psicólogo'),
('Ivqaem'),
('Jnantik lu um/Madre Tierra'),
('John Constantine'),
('Kim'),
('La chispa adecuada'),
('La guerra'),
('La noche en que José Eutanasio debió decir adiós'),
('La poesía destruye'),
('La regadera'),
('La trupé esquiva'),
('Línea B'),
('Lo que me pone de ti'),
('Locos'),
('Manos vacías'),
('Manto de llamas'),
('Mares do Brasil'),
('María Marioneta'),
('Matria'),
('Me dejaste como un estúpido'),
('Me siento raro aquí/Éter'),
('Medias naranjas'),
('Mega ciudad'),
('Mi Erick'),
('Microdiccionario'),
('Microondas'),
('Miedo'),
('Mis novios, mis novias y yo'),
('Mis poemas también expiran'),
('Mnmn'),
('Mujer'),
('Nacido en México'),
('Nació en el espacio'),
('No ser'),
('No toques el mito'),
('Noches'),
('Nuestro amor es clientelar'),
('Nuestro amor no aguantó la cumbia'),
('Nuevo sencillo de Björk, Tenochtikyavik. Dirige Alejandro Jodorowsky'),
('Octubre negro'),
('Oda rápida a Salvador Díaz Mirón'),
('Open Diving'),
('Otro origen'),
('Pantalones anchos'),
('Para poetas pulqueros'),
('Parte I - La universidad. La universidad - Parte I'),
('Penitencia'),
('Pensé tu cuerpo'),
('Personal Jesus'),
('Petra'),
('Play'),
('Podría ocurrir'),
('Poema, instrucciones de uso'),
('Poesía'),
('"Poetas, si la palabra..."'),
('Porque la tierra negra cubrirá tus pasos'),
('Posibilidades'),
('Prakerty'),
('Profecía'),
('Profecía'),
('Proporcionalidad de la decepción'),
('Puta sin esquina'),
('Radiotransmisor'),
('RAM Charger'),
('Réplicas de vecindario'),
('Réquiem for Hello, Barbie'),
('Roces de lenguas'),
('Roedores'),
('Rosarito'),
('Rugido'),
('Scape'),
('Segundo con vos'),
('Ser humano desechable'),
('Serpiente'),
('Shhh!'),
('Sin título, como yo'),
('Sniper'),
('Soledad/Natura'),
('Sólo después del golpe siento el momento'),
('Somos los que empuñamos el micro'),
('Soy el ciudadano promedio'),
('Suelo llorar'),
('Tejidos del aire'),
('Time Line'),
('Todos somos poetas'),
('Toxic'),
('Tráiganme a una persona'),
('Traigo noticias'),
('Tu pene sabe a gloria'),
('Tus manos mágicas'),
('Una búsqueda'),
('"Una serpiente que muerde su cola..."'),
('Viajero'),
('Virgo: Todas las madres son tierra'),
('Volamos juntos'),
('Yo'),
('Yo ando descalza'),
('Yo soy Jack el maltripeador'),
('Yo vivo del sol naciente'),
('YouPorn');

INSERT INTO composicion (nom_tit, tit_alt) VALUES
('Nico', 'Dime mamá'),
('Autorreferente', 'Soy su fan'),
('INFOenza', 'La ópera de la epidemia y los medios de comunicación masiva'),
('Carbón', 'Gonzálo Rojas & Portishead Mix'),
('Poema Monoestereo', 'Tips para combatir el despotismo del macho activo'),
('Final', 'versión Alejandro');

INSERT INTO composicion (nom_tit, fecha_pub, lugar_comp) VALUES
('Irradiador', '1923-09-00', 58),
('Rrro', '1922-09-24', 58),
('De "Bacantes"', '1982-00-00', 58),
('De "Jaguar"', '1991-00-00', 58),
('De "Baniano"', '1986-00-00', 58),
('De "Canto malabar"', '1987-00-00', 58),
('De "Cantáridas"', '1999-00-00', 58),
('De "Ultramar. Odas"', '2002-00-00', 58),
('De "El vino de las cosas. Ditirambos"', '2004-00-00', 58),
('De "Nadir"', '2011-00-00', 58),
('De "Bomarzo"', '2009-00-00', 58),
('Esto que ves aquí no es', '1998-00-00', 58),
('Una avispa sobre el agua', '1998-00-00', 58),
('Mariposa', '1998-00-00', 58),
('Desde esta luz', '1998-00-00', 58),
('Como esbozos', '2007-00-00', 58),
('Entre estas ruinas', '2007-00-00', 58),
('Que caiga esa lluvia fina', '2007-00-00', 58),
('Toca su fondo y se mueve', '2007-00-00', 58),
('El canto del gallo', '2007-00-00', 58),
('Ese espacio, ese jardín. Parte IX, fragmento', '2003-00-00', 58),
('Hilo en una tela de araña', '1998-00-00', 58),
('El hipotético espectador', '1998-00-00', 58),
('Una piedra en el agua de la cordura', '1998-00-00', 58),
('Todo lo desdice el silencio', '2007-00-00', 58),
('Piedra en la arena', '1998-00-00', 58),
('Peces de piel fugaz', '1977-00-00', 58),
('Deja que esparzan su humedad de batracios', '1977-00-00', 58),
('La voz indígena', '1998-00-00', 58),
('Los cuartos no son como deben ser', '2007-00-00', 58),
('Ese espacio, ese jardín. Partes II y III, fragmentos', '2003-00-00', 58);

INSERT INTO composicion (nom_tit, fecha_pub, lugar_comp) VALUES
('Manifiesto Estridentista. Actual no. 1', '1921-12-00', 58),
('En la entraña del tiempo', '1994-00-00', 58),
('En esta oscura mezquita fría', '1982-00-00', 58),
('Agua de bordes lúbricos', '1982-00-00', 58),
('Me refracta a tu vida como a un enigma', '1982-00-00', 58),
('Los ríos encrespan un follaje de calma', '1982-00-00', 58),
('Poblaciones lejanas', '1982-00-00', 58),
('Dame, tierra, tu noche', '2010-00-00', 58);