INSERT INTO familia_instrumento (nom_familia_instr) VALUES
('Ninguno'),
('Desconocido'),
('Otro'),
('Viento metal'),
('Viento madera'),
('Viento general'),
('Cuerda'),
('Percusión membranófono'),
('Percusión idiófono'),
('Percusión corporal'),
('Percusión general'),
('Teclado'),
('Electrónico'),
('Programa de computadora'),
('Unidad de efectos');