INSERT INTO genero_musical (nom_gen_mus, coment_gen_mus) VALUES
('Poesía', 'Género literario que difiere de la narrativa y de la dramaturgia en el hecho de que no necesariamente requiere de una secuencialidad u orden lógico para crear nuevos mundos'),
('Poesía sonora', 'Poesía en cuya creación los aspectos de la sonoridad y la plasticidad del lenguaje son más preponderantes que las del sentido o la significación'),
('Spoken Word', 'Nombre que se le da en países anglófonos a ciertas manifestaciones poéticas en voz alta. También se refiere a los fragmentos vocales no cantados en una canción'),
('Slam de poesía', 'Evento colectivo de declamación de poesía en voz alta con reglas específicas para la presentación y evaluación de cada participante'),
('Rap', 'Manifestación cultural urbana originada entre las comunidades afrodescendientes de Estados Unidos. Generalmente se le confunde con hip-hop, su manifestación musical'),
('Hip Hop', 'Manufestación musical de la cultura rap, con alta preponderancia de la palabra y con ritmos acompasados'),
('Composición sonoro-textual', 'Nombre propuesto por el poeta canadiense Paul Dutton para referirse a las composiciones interdisciplinarias que combinan música o arte sonoro con poesía'),
('Poesía zapoteca', 'Poesía en lengua zapoteca'),
('Poesía tojolabal', 'Poesía en lengua tojolabal'),
('Poesía náhuatl', 'Poesía en lengua náhuatl'),
('Poesía totonaca', 'Poesía en lengua totonaca'),
('Son jarocho', 'Estilo musical típico del estado de Veracruz, cuyas características líricas incluyen una métrica altamente estructurada, rima consonante y un gran repertorio temático'),
('Valona michoacana', 'Forma musical y literaria típica del estado de Michoacán, cuya estructura métrica consiste en estrofas de dies versos octosílabos'),
('Corrido', 'Versión mexicana del romance español que conserva la rima anisosilábica y versos por lo general octosílabos'),
('Minificción', 'Género literario breve con inclinación a la narrativa, de carácter lúdico, irónico, metaficcional e híbrido'),
('Canción', 'Composición musical para voz humana, con contenido textual (letra) y comúnmente acompañada por instrumentos musicales. La entonación vocal observa una amplia tesitura'),
('Poesía modernista', 'Poesía escrita por autores identificados con el movimiento hispanoamericano del modernismo (finales del siglo XIX)'),
('Arte sonoro', 'Prácticas artísticas cuyos principales ejes de acción son el sonido, la escucha y la audición'),
('Música acusmática', 'Tipo de música electroacústica compuesta para ser reproducida por medio de altavoces'),
('Performance', 'Muestra artística de corte escénico, usualmente con altos niveles de improvisación, en la que el cuerpo y su materialidad juegan un papel preponderante'),
('Teatro', 'Rama de las artes escénicas enfocada en la actuación'),
('Narrativa', 'Género literario de corte secuencial, con alta propensión a desarrollar historias o acontecimientos'),
('Música electrónica', 'Música que para su creación emplea instrumentos y tecnología musical electrónica'),
('Música experimental', 'Término introducido por el músico estadounidense John Cage para referirse a toda música que produce resultados no previsibles y que busca desafiar las nociones preestablecidas sobre la música'),
('Jazz', 'Surgido entre las comunidades comunidades afrodescendientes de Estados Unidos, con alta propensión a la improvisación y a la mezcla de elementos típicos de la música occidental (melodía, armonía) con la afroamericana (ritmo, fraseo)'),
('Rock', 'Género ecléctico con fuerte influencia del blues y el country, pero que se ha extendido más allá de dichos horizontes. Una de sus características principales es la preponderancia de la guitarra como instrumento principal'),
('Pop', 'Género musical cuyas composiciones son generalmente de corta duración, con una estructura básica verso-estribillo, y uso habitual de motifs repetitivos'),
('Radioarte', 'Se refiere al uso de la radio con fines artísticos, así como a las piezas creativas sonoras pensadas específicamente para su transmisión por radio'),
('Paisaje sonoro', 'Una forma de arte sonoro-musical electrónico o electroacústico que utiliza grabaciones sonoras de lugares y espacios de diversa índole, ya sean naturaes o modificados por el humano'),
('Caminata sonora', 'Consiste en una excursión sonora en silencio para escuchar y apreciar los sonidos de un lugar o recorrido'),
('Samba', 'El género musical y dancístico más famoso de Brasil, con raíces africanas y diversas variantes regionales');
