INSERT INTO lugar (ciudad, subdivision, pais) VALUES
('París', 'Île-de-France', 'Francia'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Orizaba', 'Veracruz', 'México'),
('Texcoco', 'Estado de México', 'México'),
('Papantla', 'Veracruz', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Veracruz', 'Veracruz', 'México'),
('Veracruz', 'Veracruz', 'México'),
('Tuxtla Gutiérrez', 'Chiapas', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Guanajuato', 'Guanajuato', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Uruapan', 'Michoacán', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Sayula', 'Jalisco', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Lawrence', 'Massachusetts', 'Estados Unidos'),
('Nueva York', 'Nueva York', 'Estados Unidos'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Morelia', 'Michoacán', 'México'),
('Veracruz', 'Veracruz', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Juchitán', 'Oaxaca', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Comitán', 'Chiapas', 'México'),
('La Habana', 'La Habana', 'Cuba'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Tombstone', 'Arizona', 'Estados Unidos'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Saltillo', 'Coahuila', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Guadalajara', 'Jalisco', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Oaxaca', 'Oaxaca', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('París', 'Île-de-France', 'Francia'),
('Nueva York', 'Nueva York', 'Estados Unidos'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad Nezahualcóyotl', 'Estado de México', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Torreón', 'Coahuila', 'México'),
('San Luis Potosí', 'San Luis Potosí', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Wallsend', 'Northumberland', 'Inglaterra'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Montreal', 'Quebec', 'Canadá'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Tijuana', 'Baja California', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Cuernavaca', 'Morelos', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Gotemburgo', 'Västra Götaland', 'Suecia'),
('Berlin', 'Berlin', 'Alemania'),
('Sea Ranch', 'California', 'Estados Unidos'),
('San Bruno', 'California', 'Estados Unidos'),
('Ciudad de México', 'Distrito Federal', 'México'),
('Ciudad de México', 'Distrito Federal', 'México');