INSERT INTO lugar (ciudad, nom_subdivision, tipo_subdivision, pais) VALUES
(NULL, NULL, NULL, NULL),
(NULL, NULL, 'Estado', 'México'),
(NULL, NULL, 'Estado', 'Estados Unidos'),
(NULL, NULL, NULL, 'Argentina'),
(NULL, NULL, NULL, 'Chile'),
(NULL, NULL, NULL, 'Perú'),
(NULL, NULL, NULL, 'Guatemala'),
(NULL, NULL, 'Departamento', 'Colombia'),
(NULL, NULL, NULL, 'Uruguay'),
(NULL, NULL, NULL, 'Brasil'),
(NULL, NULL, NULL, 'Venezuela'),
(NULL, NULL, NULL, 'El Salvador'),
(NULL, NULL, 'Provincia', 'Cuba'),
(NULL, NULL, NULL, 'Puerto Rico'),
(NULL, NULL, NULL, 'Nicaragua'),
(NULL, NULL, 'Provincia', 'Canadá'),
(NULL, NULL, NULL, 'España'),
(NULL, NULL, NULL, 'Honduras'),
(NULL, NULL, NULL, 'Panamá'),
(NULL, NULL, NULL, 'Costa Rica'),
(NULL, NULL, NULL, 'Dominicana, República'),
(NULL, NULL, NULL, 'Haití'),
(NULL, NULL, NULL, 'Bolivia'),
(NULL, NULL, NULL, 'Paraguay'),
(NULL, NULL, NULL, 'Ecuador'),
(NULL, 'Aguascalientes', 'Estado', 'México'),
(NULL, 'Baja California', 'Estado', 'México'),
(NULL, 'Baja California Sur', 'Estado', 'México'),
(NULL, 'Campeche', 'Estado', 'México'),
(NULL, 'Chiapas', 'Estado', 'México'),
(NULL, 'Chihuahua', 'Estado', 'México'),
('Torreón', 'Coahuila', 'Estado', 'México'),
(NULL, 'Coahuila', 'Estado', 'México'),
(NULL, 'Colima', 'Estado', 'México'),
(NULL, 'Durango', 'Estado', 'México'),
(NULL, 'Guanajuato', 'Estado', 'México'),
(NULL, 'Guerrero', 'Estado', 'México'),
(NULL, 'Hidalgo', 'Estado', 'México'),
(NULL, 'Jalisco', 'Estado', 'México'),
(NULL, 'Estado de México', 'Estado', 'México'),
(NULL, 'Michoacán', 'Estado', 'México'),
(NULL, 'Morelos', 'Estado', 'México'),
(NULL, 'Nayarit', 'Estado', 'México'),
(NULL, 'Nuevo León', 'Estado', 'México'),
(NULL, 'Oaxaca', 'Estado', 'México'),
(NULL, 'Puebla', 'Estado', 'México'),
(NULL, 'Querétaro', 'Estado', 'México'),
(NULL, 'Quintana Roo', 'Estado', 'México'),
(NULL, 'San Luis Potosí', 'Estado', 'México'),
(NULL, 'Sinaloa', 'Estado', 'México'),
(NULL, 'Sonora', 'Estado', 'México'),
(NULL, 'Tabasco', 'Estado', 'México'),
(NULL, 'Tamaulipas', 'Estado', 'México'),
(NULL, 'Tlaxcala', 'Estado', 'México'),
(NULL, 'Veracruz', 'Estado', 'México'),
(NULL, 'Yucatán', 'Estado', 'México'),
(NULL, 'Zacatecas', 'Estado', 'México'),
('Ciudad de México', 'Distrito Federal', 'Estado', 'México'),
('Morelia', 'Michoacán', 'Estado', 'México'),
('Xalapa', 'Veracruz', 'Estado', 'México'),
('Guanajuato', 'Guanajuato', 'Estado', 'México'),
('París', 'Île-de-France', 'Región', 'Francia'),
('Uruapan', 'Michoacán', 'Estado', 'México'),
('Veracruz', 'Veracruz', 'Estado', 'México'),
('Tombstone', 'Arizona', 'Estado', 'Estados Unidos'),
('Saltillo', 'Coahuila', 'Estado', 'México'),
('Guadalajara', 'Jalisco', 'Estado', 'México'),
('Ciudad Nezahualcóyotl', 'Estado de México', 'Estado', 'México'),
('Tijuana', 'Baja California', 'Estado', 'México'),
('Rosarito', 'Baja California', 'Estado', 'México'),
('Cuernavaca', 'Morelos', 'Estado', 'México'),
('Ciudad Juárez', 'Chihuahua', 'Estado', 'México'),
('Chihuahua', 'Chihuahua', 'Estado', 'México'),
('San Cristóbal de las Casas', 'Chiapas', 'Estado', 'México'),
('Oaxaca', 'Oaxaca', 'Estado', 'México'),
('Tlaxcala', 'Tlaxcala', 'Estado', 'México'),
('Ciudad Victoria', 'Tamaulipas', 'Estado', 'México'),
('Aguascalientes', 'Aguascalientes', 'Estado', 'México'),
('Mexicali', 'Baja California', 'Estado', 'México'),
('Ensenada', 'Baja California', 'Estado', 'México'),
('Campeche', 'Campeche', 'Estado', 'México'),
('Tuxtla Gutiérrez', 'Chiapas', 'Estado', 'México'),
('Colima', 'Colima', 'Estado', 'México'),
('Manzanillo', 'Colima', 'Estado', 'México'),
('Navachiste', 'Sinaloa', 'Estado', 'México'),
('Durango', 'Durango', 'Estado', 'México'),
('León', 'Guanajuato', 'Estado', 'México'),
('Chilpancingo', 'Guerrero', 'Estado', 'México'),
('Acapulco', 'Guerrero', 'Estado', 'México'),
('Pachuca', 'Hidalgo', 'Estado', 'México'),
('Tequila', 'Jalisco', 'Estado', 'México'),
('Toluca', 'Estado de México', 'Estado', 'México'),
('Ecatepec', 'Estado de México', 'Estado', 'México'),
('Metepec', 'Estado de México', 'Estado', 'México'),
('Tepoztlán', 'Morelos', 'Estado', 'México'),
('Tepic', 'Nayarit', 'Estado', 'México'),
('Monterrey', 'Nuevo León', 'Estado', 'México'),
('Puebla', 'Puebla', 'Estado', 'México'),
('Querétaro', 'Querétaro', 'Estado', 'México'),
('Chetumal', 'Quintana Roo', 'Estado', 'México'),
('Cancún', 'Quintana Roo', 'Estado', 'México'),
('San Luis Potosí', 'San Luis Potosí', 'Estado', 'México'),
('Culiacán', 'Sinaloa', 'Estado', 'México'),
('Mazatlán', 'Sinaloa', 'Estado', 'México'),
('Puerto Vallarta', 'Jalisco', 'Estado', 'México'),
('Hermosillo', 'Sonora', 'Estado', 'México'),
('Villahermosa', 'Tabasco', 'Estado', 'México'),
('Reynosa', 'Tamaulipas', 'Estado', 'México'),
('Matamoros', 'Tamaulipas', 'Estado', 'México'),
('Nuevo Laredo', 'Tamaulipas', 'Estado', 'México'),
('Jerez', 'Zacatecas', 'Estado', 'México'),
('Mérida', 'Yucatán', 'Estado', 'México'),
('Chichen Itzá', 'Yucatán', 'Estado', 'México'),
('Teotihuacán', 'Estado de México', 'Estado', 'México'),
('Berlín', 'Berlín', 'Estado', 'Alemania'),
('Sea Ranch', 'California', 'Estado', 'Estados Unidos'),
('San Bruno', 'California', 'Estado', 'Estados Unidos'),
('San Francisco', 'California', 'Estado', 'Estados Unidos'),
('Los Ángeles', 'California', 'Estado', 'Estados Unidos'),
('San Diego', 'California', 'Estado', 'Estados Unidos'),
('Chula Vista', 'California', 'Estado', 'Estados Unidos'),
('San Ysidro', 'California', 'Estado', 'Estados Unidos'),
('Montreal', 'Quebec', 'Provincia', 'Canadá'),
('Tecate', 'Baja California', 'Estado', 'México'),
('La Paz', 'Baja California Sur', 'Estado', 'México'),
('Comitán', 'Chiapas', 'Estado', 'México'),
('La Habana', 'La Habana', 'Provincia', 'Cuba'),
(NULL, NULL, 'Región', 'Francia'),
('Juchitán', 'Oaxaca', 'Estado', 'México'),
('Sayula', 'Jalisco', 'Estado', 'México'),
('Lawrence', 'Massachusetts', 'Estado', 'Estados Unidos'),
('Nueva York', 'Nueva York', 'Estado', 'Estados Unidos'),
('Orizaba', 'Veracruz', 'Estado', 'México'),
('Texcoco', 'Estado de México', 'Estado', 'México'),
('Wallsend', 'Northumberland', 'Condado', 'Inglaterra'),
('Gotemburgo', 'Västra Götaland', 'Provincia', 'Suecia'),
('Papantla', 'Veracruz', 'Estado', 'México');
