INSERT INTO pais VALUES
('Afganistán'),
('Albania'),
('Argelia'),
('Samoa Americana'),
('Andorra'),
('Angola'),
('Anguilla'),
('Antártida'),
('Antigua y Barbuda'),
('Argentina'),
('Armenia'),
('Aruba'),
('Australia'),
('Austria'),
('Azerbaiyán'),
('Bahamas'),
('Bahrein'),
('Bangladesh'),
('Barbados'),
('Bielorrusia'),
('Bélgica'),
('Belice'),
('Benín'),
('Bermudas'),
('Bután'),
('Bolivia'),
('Bosnia-Herzegovina'),
('Botswana'),
('Brasil'),
('Brunei Darussalam'),
('Bulgaria'),
('Burkina Faso'),
('Burundi'),
('Camboya'),
('Camerún'),
('Canadá'),
('Cabo Verde'),
('Islas Caimán'),
('República Centroafricana'),
('Chad'),
('Chile'),
('China'),
('Isla De Navidad, Isla Christmas'),
('Islas Cocos'),
('Colombia'),
('Comores'),
('República Democrática del Congo'),
('República del Congo'),
('Islas Cook'),
('Costa Rica'),
('Costa de Marfil'),
('Croacia'),
('Cuba'),
('Chipre'),
('República Checa'),
('Dinamarca'),
('Djibouti, Yibuti'),
('Dominica'),
('Dominicana, República'),
('Timor Oriental'),
('Ecuador'),
('Egipto'),
('El Salvador'),
('Guinea Ecuatorial'),
('Eritrea'),
('Estonia'),
('Etiopía'),
('Islas Malvinas'),
('Islas Feroe'),
('Fiyi'),
('Finlandia'),
('Francia'),
('Guayana Francesa'),
('Polinesia Francesa'),
('Tierras Australes y Antárticas Francesas'),
('Gabón'),
('Gambia'),
('Georgia'),
('Alemania'),
('Ghana'),
('Gibraltar'),
('Gran Bretaña'),
('Grecia'),
('Groenlandia'),
('Granada'),
('Guadalupe'),
('Guam'),
('Guatemala'),
('República Guinea'),
('Guinea Bissau'),
('Guyana'),
('Haití'),
('Inglaterra'),
('Santa Sede, Vaticano, Ciudad del Vaticano'),
('Honduras'),
('Hong Kong'),
('Hungría'),
('Islandia'),
('India'),
('Indonesia'),
('Irán'),
('Iraq'),
('Irlanda'),
('Israel'),
('Italia'),
('Jamaica'),
('Japón'),
('Jordania'),
('Kazajstán'),
('Kenia'),
('Kiribati'),
('Corea del Norte'),
('Corea del Sur'),
('Kosovo'),
('Kuwait'),
('Kirguistán'),
('Laos; oficialmente: República Democrática Popular Lao'),
('Letonia'),
('Líbano'),
('Lesotho'),
('Liberia'),
('Libia'),
('Liechtenstein'),
('Lituania'),
('Luxemburgo '),
('Macao'),
('Macedonia'),
('Madagascar'),
('Malawi'),
('Malasia'),
('Maldivas'),
('Malí'),
('Malta'),
('Islas Marshall'),
('Martinica'),
('Mauritania'),
('Mauricio'),
('Mayotte'),
('México'),
('Micronesia, Estados Federados de'),
('Moldavia'),
('Mónaco'),
('Mongolia'),
('Montenegro'),
('Montserrat'),
('Marruecos'),
('Mozambique'),
('Myanmar, Birmania'),
('Namibia'),
('Nauru'),
('Nepal'),
('Países Bajos, Holanda'),
('Antillas Holandesas'),
('Nueva Caledonia'),
('Nueva Zelanda'),
('Nicaragua'),
('Niger'),
('Nigeria'),
('Niue'),
('Marianas del Norte'),
('Noruega'),
('Omán'),
('Pakistán'),
('Palau'),
('Territorios Palestinos'),
('Panamá'),
('Papúa-Nueva Guinea'),
('Paraguay'),
('Perú'),
('Filipinas'),
('Isla Pitcairn'),
('Polonia'),
('Portugal'),
('Puerto Rico'),
('Qatar'),
('Reunión'),
('Rumanía'),
('Federación Rusa'),
('Ruanda'),
('San Cristobal y Nevis'),
('Santa Lucía'),
('San Vincente y Granadinas'),
('Samoa'),
('San Marino'),
('Santo Tomé y Príncipe'),
('Arabia Saudita'),
('Senegal'),
('Serbia'),
('Seychelles'),
('Sierra Leona'),
('Singapur'),
('Eslovaquia'),
('Eslovenia'),
('Islas Salomón'),
('Somalia'),
('Sudáfrica'),
('Sudán del Sur'),
('España'),
('Sri Lanka'),
('Sudán'),
('Surinam'),
('Swazilandia'),
('Suecia'),
('Suiza'),
('Siria'),
('Taiwan'),
('Tadjikistan'),
('Tanzania'),
('Tailandia'),
('Tíbet'),
('Togo'),
('Tokelau'),
('Tonga'),
('Trinidad y Tobago'),
('Túnez'),
('Turquía'),
('Turkmenistan'),
('Islas Turcas y Caicos'),
('Tuvalu'),
('Uganda'),
('Ucrania'),
('Emiratos Árabes Unidos'),
('Reino Unido'),
('Estados Unidos'),
('Uruguay'),
('Uzbekistán'),
('Vanuatu'),
('Ciudad del Vaticano'),
('Venezuela'),
('Vietnam'),
('Islas Virgenes Británicas'),
('Islas Virgenes Americanas'),
('Wallis y Futuna'),
('Sáhara Occidental'),
('Yemen'),
('Zambia'),
('Zimbabwe');
