INSERT INTO serie (nom_serie, giro) VALUES
('Poetas en abril: 24 horas de poesía 2004', 'Programa radiofónico'),
('César Cortés piezas sueltas', 'Colección sonora'),
('Enclave 2015', 'Festival'),
('Radiopoemario', 'Programa radiofónico'),
('Edmeé García piezas sueltas', 'Colección sonora'),
('eSLAMex 1', 'Álbum'),
('Eslam de poesía #25 Rojo Córdova CCD', 'Slam de poesía'),
('Eslam de poesía #26 Rojo Córdova CCD', 'Slam de poesía'),
('Eslam de poesía #27 Rojo Córdova CCD', 'Slam de poesía'),
('Eslam de poesía #28 Rojo Córdova CCD', 'Slam de poesía'),
('Eslam de poesía #29 Rojo Córdova CCD', 'Slam de poesía'),
('Eslam de poesía #31 Rojo Córdova CCD', 'Slam de poesía'),
('Eslam de poesía #33 Rojo Córdova CCD', 'Slam de poesía'),
('Salvajes de Ciudad AKA', 'Concierto'),
('KFGC en Foro Hilvana', 'Concierto'),
('Presentación de "La Sentidora" en Foro Hilvana', 'Concierto'),
('Sesión ICBC Tecate', 'Concierto'),
('Tour Negativo (-T)', 'Concierto'),
('KFGC piezas sueltas', 'Colección sonora'),
('Voz viva de México', 'Colección sonora'),
('Frágil', 'Álbum'),
('La tierra prometida', 'Álbum');