INSERT INTO serie (nom_serie, giro, lugar_id) VALUES
('Poetas en abril: 24 horas de poesía 2004', 'Programa radiofónico', 58),
('César Cortés piezas sueltas', 'Colección sonora', 58),
('Enclave 2015', 'Festival', 58), 
('Radiopoemario', 'Programa radiofónico', 58),
('Edmeé García piezas sueltas', 'Colección sonora', 58),
('eSLAMex 1', 'Álbum', 58),
('Eslam de poesía #25 Rojo Córdova CCD', 'Slam de poesía', 58),
('Eslam de poesía #26 Rojo Córdova CCD', 'Slam de poesía', 58),
('Eslam de poesía #27 Rojo Córdova CCD', 'Slam de poesía', 58),
('Eslam de poesía #28 Rojo Córdova CCD', 'Slam de poesía', 58),
('Eslam de poesía #29 Rojo Córdova CCD', 'Slam de poesía', 58),
('Eslam de poesía #31 Rojo Córdova CCD', 'Slam de poesía', 58),
('Eslam de poesía #33 Rojo Córdova CCD', 'Slam de poesía', 58),
('Salvajes de Ciudad AKA', 'Álbum', 58),
('KFGC en Foro Hilvana', 'Concierto', 58),
('Presentación de "La Sentidora" en Foro Hilvana', 'Concierto', 58),
('Sesión ICBC Tecate', 'Concierto', 124),
('Tour Negativo (-T)', 'Concierto', 58),
('KFGC piezas sueltas', 'Colección sonora', 58),
('Voz viva de México', 'Colección sonora', 58),
('Frágil', 'Álbum', 60);