\i populate/idioma.sql
\i populate/genero_musical.sql
\i populate/familia_instrumento.sql
\i populate/instrumento.sql
\i populate/tema.sql
\i populate/serie.sql
\i populate/persona.sql
\i populate/grupo.sql
\i populate/album.sql
--\i populate/composicion.sql
--\i populate/pista_son.sql
--\i populate/composicion_autor.sql
--\i populate/interpretacion.sql
--\i populate/artista_colectivo.sql
