\i populate/lugar.sql
\i populate/colectivo.sql
\i populate/tipo_institucion.sql
\i populate/institucion.sql
\i populate/editor.sql
\i populate/serie.sql
\i populate/idioma.sql
\i populate/genero_musical.sql
\i populate/familia_instrumento.sql
\i populate/instrumento.sql
\i populate/tipo_artista.sql
\i populate/artista.sql
\i populate/album.sql
\i populate/tema.sql
